option(
    'build-python',
    type: 'boolean',
    value: true,
    description:
        'Whether to build the Cython extension modules. ' +
        'The Python files are not "built", but without the Cython modules ' +
        'the Python package is malformed and therefore not installed.',
)
option(
    'build-tests',
    type: 'feature',
    value: 'auto',
    description:
        'Whether to build the C++ tests.' +
        'When set to enabled, the tests are always built.' +
        'When set to disabled, the tests are never built.' +
        'When set to auto (default), the tests are built when buildtype != release.',
)
